import {
  Apilogin,
  Apiregister,
  ApichangeAvatar,
  ApigetAvatar,
  ApigetHotMovies,
  ApigetRecommendMovies,
  ApigetAllMovies,
  Apisearchmovies,
  Apiselectmovie,
  ApisaveUserinfo,
  ApiGetUserinfo,
  ApigetConsultation,
  ApieditUser,
  ApigetAllUser,
  ApideltUser,
  ApichangeMovie,
  ApideltMovie,
  ApiaddMovie,
  ApiaddConsultation,
  ApideltConsultation,
  ApichangeConstation
} from "./auth";
import { handleError } from "./errorHandler";

export {
  Apilogin,
  Apiregister,
  ApichangeAvatar,
  ApigetAvatar,
  ApigetHotMovies,
  ApigetRecommendMovies,
  ApigetAllMovies,
  Apisearchmovies,
  Apiselectmovie,
  ApisaveUserinfo,
  ApiGetUserinfo,
  ApigetConsultation,
  ApieditUser,
  ApigetAllUser,
  ApideltUser,
  ApiaddMovie,
  ApichangeMovie,
  ApideltMovie,
  ApiaddConsultation,
  ApideltConsultation,
  ApichangeConstation,
  handleError,
};
