system:
 ip: "127.0.0.1"
 port: 8080
 env: "dev"

mysql:
 host: 127.0.0.1
 port: 3306
 config: ""
 db: "movies"
 username: root
 password: 123456
 max-idle-conns: 10
 max-open-conns: 100
 log-mode: error

redis:
 ip: "127.0.0.1"
 port: 8080
 password: "Lgy20020624."
 PoolSize: 500
 
jwt:
 exp: 8
 iss: "lgynb"
 secret: "qwertyuiopasdfghjkl"